<?php


namespace App\Udi\Http\Controllers\Custom;


use App\Udi\Http\Controllers\AbstractCustomWorkspaceController;
use Illuminate\Http\Request;

class ScheduleEditorController extends AbstractCustomWorkspaceController
{

    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function load(Request $request)
    {

    }

    protected function getParentWorkspaceData()
    {
        return [
            'workspace' => 'StudentClasses',
            'id' => $this->request->student_class_id
        ];
    }
}